Using TensorFlow backend.
Loading word vector model, please wait...
Traceback (most recent call last):
  File "/Users/MacBookAir/Downloads/SentiBot/SentiBot.py", line 15, in <module>
    database='./db.sqlite3')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chatterbot/chatterbot.py", line 32, in __init__
    wordSegmenter.build(learn_context_weights=True)
  File "/Users/MacBookAir/Downloads/SentiBot/word_segmenter.py", line 56, in build
    activation='tanh')(embed_forward)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/topology.py", line 511, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/topology.py", line 569, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/layers/recurrent.py", line 236, in call
    input_length=input_shape[1])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 1032, in rnn
    mask_list = tf.unpack(mask)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 623, in unpack
    raise ValueError("Cannot infer num from shape %s" % value_shape)
ValueError: Cannot infer num from shape (?, ?, 1)
